version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database_development
    ports:
      - '5432:5432'
    volumes: 
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  api:
    container_name: api
    build:
      context: .
    image: dockerfile
    depends_on:
      - db
    ports:
      - 3030:3030
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: database_development
    links:
      - db
    volumes:
      - './:/src'
      
volumes:
  db:
    driver: local
